Added support for 'event' functions
oci-labs/rmw_opendds pull request #44
Opened 2020-06-16 20:56 UTC by kuznetsovmoci

Please review this draft for added 'event' functions. There is also one 'TODO' section that needs to be resolved with some added use of OpenDDS.

2020-06-16 22:32 UTC, mitza-oci requested changes

2020-06-16 22:32 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/event_converter.hpp
> +//#include "ndds_include.hpp"
remove these lines

2020-06-16 22:32 UTC, mitza-oci commented on rmw_opendds_shared_cpp/src/event.cpp
> +  // if ret_code is not okay, return error and set taken to false.
Is the comment telling us anything additional to just reading the simple line of code below?

2020-06-16 22:32 UTC, mitza-oci commented on rmw_opendds_shared_cpp/src/event_converter.cpp
> +//rmw_ret_t check_dds_ret_code(const DDS::ReturnCode_t dds_return_code)
remove?

2020-06-17 13:26 UTC, mitza-oci requested changes

2020-06-17 13:26 UTC, mitza-oci commented on rmw_opendds_shared_cpp/src/event.cpp
> +//#include "rmw_connext_shared_cpp/connext_static_event_info.hpp"
remove

2020-06-17 13:26 UTC, mitza-oci commented on rmw_opendds_shared_cpp/src/event.cpp
> +    // TODO: implement
Is this something that will be implemented in this PR or at another time?

2020-06-18 19:22 UTC, adamsj-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/wait.hpp
> +      //}
What's this commented section for? Is this a TODO or dead code we don't need anymore?

2020-06-18 19:22 UTC, adamsj-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/wait.hpp
> +      // reset the subscriber handle
TODO or dead code?

2020-06-18 19:22 UTC, adamsj-oci commented on rmw_opendds_shared_cpp/src/event.cpp
> +  // TODO: uncomment and remove next line
@kuznetsovmoci When do we uncomment?

2020-06-19 15:56 UTC, mitza-oci approved these changes

2020-06-24 15:24 UTC, mitza-oci requested changes
the Builtintopickey/instancehandle/guid stuff needs to be cleaned up

2020-06-24 15:24 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
I don't know how this is used by the rest of the RMW, but this is not a general way of translating a builtInTopicKey to a GUID.

2020-06-24 15:24 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/opendds_static_event_info.hpp
> +typedef struct OpenDDSCustomEventInfo
`typedef struct` is from C, no need for it here.

2020-06-24 15:24 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/qos.hpp
> +    // RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_NODE has been depricated: use RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_TOPIC below
remove these?

2020-06-24 15:24 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/types.hpp
> +    const DDS::GUID_t& instance_handle,
Why is the name `instance_handle` if it's not one?

2020-06-24 16:02 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
This is about the only information I was able to find:
https://community.rti.com/kb/accessing-guid-connext-dds-entities

2020-06-24 16:04 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
I haven't read it but I have to assume it doesn't apply to OpenDDS.  As I put in the overall comment - this needs some design work.  Why is BuiltinTopicKey needed?  Is it sufficient to just use InstanceHandle and GUID?

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_cpp/src/opendds_static_subscriber_info.cpp
> +// Copyright 2014-2019 Open Source Robotics Foundation, Inc.
Do the OSRF copyrights belong in these repos?

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
>  //  Taken from http://community.rti.com/comment/689#comment-689
keep?

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/opendds_static_event_info.hpp
> +typedef struct OpenDDSCustomEventInfo
The name of this class makes it sound like it should be in the OpenDDS repo. Might be better for tracing code to insert "RMW" somewhere in the name.

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/qos.hpp
> +    //  break;
TODO?

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/qos.hpp
> +    // RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_NODE has been depricated: use RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_TOPIC if manually asserted liveliness is needed.
```suggestion
    // RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_NODE has been deprecated: use RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_TOPIC if manually asserted liveliness is needed.
```

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/topic_cache.hpp
> +      TopicInfo{ topic_name, type_name, participant_guid, endpoint_guid};
Looks like the commented line needs to be removed?

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/topic_endpoint_info.hpp
> +// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
?

2020-06-24 17:41 UTC, adamsj-ros commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/topic_endpoint_info.hpp
> +#include "rmw_opendds_shared_cpp/visibility_control.h"
generally prefer <> when not local includes.

2020-06-24 20:08 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
How can I get Participant's InstanceHandle from on_data_available()?...

2020-06-24 20:10 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
https://github.com/kuznetsovmoci/rmw_opendds/blob/6e9ad6da971c862390b3393d15d68a0e63fad309/rmw_opendds_shared_cpp/src/types/custom_publisher_listener.cpp#L60

2020-06-24 20:15 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
Only way I can think of is storing it in the listener object, when node creates it...

2020-06-24 20:41 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
Which participant does it need to know about, and what exactly does it need (GUID)?

2020-06-24 20:41 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/opendds_static_event_info.hpp
> +typedef struct OpenDDSCustomEventInfo
Not sure I agree here, we tend to use namespaces for that kind of thing.

2020-06-24 20:59 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
GUID of the DomainParticipant to which the DataReader (Writer) belongs

2020-06-24 21:09 UTC, mitza-oci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
I don't have enough context to understand what's going on here, and a PR review is not the right place to do design discussions.  Please start a separate document for this.

2020-06-25 13:15 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/topic_cache.hpp
> +      TopicInfo{ topic_name, type_name, participant_guid, endpoint_guid};
Added 'TODO:' comment

2020-06-25 15:46 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/opendds_static_event_info.hpp
> +typedef struct OpenDDSCustomEventInfo
Should put it under rmw_opendds_cpp namespace?

2020-06-25 16:03 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
>  //  Taken from http://community.rti.com/comment/689#comment-689
Will resolve when solution for DDS_BuiltinTopicKey_to_GUID is found

2020-06-25 16:07 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/topic_endpoint_info.hpp
> +#include "rmw_opendds_shared_cpp/visibility_control.h"
Done

2020-06-25 16:15 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
Created Trello card:
https://trello.com/c/t3GAGc5a/85-find-alternative-to-ddsbuiltintopickeytoguid-function

2020-06-25 16:21 UTC, jwillemsen commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
This is very likely something I noticed in the past when creating issue https://github.com/oci-labs/rmw_opendds/issues/2

2020-06-25 16:36 UTC, kuznetsovmoci commented on rmw_opendds_shared_cpp/include/rmw_opendds_shared_cpp/guid_helper.hpp
> +inline void DDS_BuiltinTopicKey_to_GUID(DDS::GUID_t* guid, DDS::BuiltinTopicKey_t builtinTopicKey)
Added this link to the Trello card

2020-06-26 18:34 UTC, adamsj-oci commented
@kuznetsovmoci I believe some items have been postponed. Could you summarize those in as a comment in this PR?

@mitza-oci Have all your requested changes been addressed to your satisfaction?

2020-06-26 19:03 UTC, kuznetsovmoci commented
There is one item remaining to be resolved after this PR is closed:
https://github.com/oci-labs/rmw_opendds/pull/44#pullrequestreview-436752098
We would need to find an alternative logic in DDS_BuiltinTopicKey_to_GUID() function, or use a key other than participant GUID in the map.

2020-06-26 19:12 UTC, adamsj-oci commented
> There is one item remaining to be resolved after this PR is closed:
> [#44 (review)](https://github.com/oci-labs/rmw_opendds/pull/44#pullrequestreview-436752098)

Is that issue captured somewhere?

2020-06-26 19:20 UTC, kuznetsovmoci commented
> > There is one item remaining to be resolved after this PR is closed:
> > [#44 (review)](https://github.com/oci-labs/rmw_opendds/pull/44#pullrequestreview-436752098)
> 
> Is that issue captured somewhere?

Yes, here: https://docs.google.com/document/d/1tg-AE0fldhpfoM-6Pf4d_h3_TnmAr4DAX4vAoKTC3zE/edit?ts=5eac9be7#bookmark=id.tktnw8o9ewtq

2020-06-26 20:12 UTC, merged